# -*- coding: utf-8 -*-
"""GridSearchCV and randomizedCV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1He0hTE_XxJPJO9RxkclraPT089od7l

# **Hyperparameter Tuning**


---



1.   GridSearchCV
2.   RandomizedSearchCV
"""

# Dependencies
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.svm import SVC

# load breast data set
breast_cancer = load_breast_cancer()

print(breast_cancer)

# loading to data frame
data_frame = pd.DataFrame(breast_cancer.data, columns = breast_cancer.feature_names)

# show first 5 rows
data_frame.head()

# adding target columns
data_frame['label'] = breast_cancer.target

# show first 5 rows with target
data_frame.head()

# how many rows and columns
data_frame.shape

# find missing value
data_frame.isnull().sum()

# checking distribution each variable
for i in data_frame.columns:
  print(data_frame[i].value_counts())

# separeting feature and target
x = data_frame.drop(columns='label', axis=1)
y = data_frame['label']

print(x)

x.shape

print(y)

y.shape

"""#**GridSearch CV**


---

gridsearch CV determining the best parameter for model
"""

# loading SVC model
model = SVC()

# hyperparameter

Parameters = {
    'kernel':['linear','poly','rbf','sigmoid'],
    'C':[1,5,10,20]
}

# grid search
grid_search = GridSearchCV(model, Parameters, cv=5)

grid_search.fit(x,y)

print(grid_search)

grid_search.cv_results_

# best parameters
best_parameters = grid_search.best_params_
print(best_parameters)

# loading cv result to data frame
result = pd.DataFrame(grid_search.cv_results_)
result.head()

# Highest accuracy
highest_accuracy = grid_search.best_score_
print(highest_accuracy)

grid_search_result = result[['param_C','param_kernel','mean_test_score','rank_test_score']]
grid_search_result

grid_search_result.shape

grid_search_result.sort_values(by='rank_test_score')

"""High Accuracy = 95.2%



Best Parameters = {'C': 10, 'kernel': 'linear'}
********************************************************************************

# **RandomizedSearchCV**
"""

# loading SVC model
model = SVC()

parameter = {
    'kernel':['linear','poly','rbf','sigmoid'],
    'C':[1,5,10,20]
}

grid_search = RandomizedSearchCV(model, parameter, cv=5)

grid_search.fit(x,y)

print(grid_search)

grid_search.cv_results_

rcv=pd.DataFrame(grid_search.cv_results_)
rcv

rcv.shape

# best parameter
best_parameter = grid_search.best_params_
print(best_parameter)

# best accuracy
best_accuracy = grid_search.best_score_
print(best_accuracy)

result = rcv[['param_C','param_kernel','mean_test_score','rank_test_score']]
result